IzvorniKod/urednistvo/urednistvo/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace urednistvo.Models
{
    public class Comment
    {
        public int CommentId { get; set; }
        public int UserId { get; set; }
        public int TextId { get; set; }    

        public string Content { get; set; }
        public DateTime Time { get; set; }

        public virtual User User { get; set; }
        public virtual Text Text { get; set; }
    }
}

IzvorniKod/urednistvo/urednistvo/Models/Text.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace urednistvo.Models
{
    public class Text
    {
        public int TextId { get; set; }

        public string Title { get; set; }
        public string Subtitle { get; set; }
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }
        public DateTime Time { get; set; }

        public int TextStatus { get; set; } //enum
        public bool WebPublishable { get; set; }
        public bool EditionPublishable { get; set; }
        public int? WantedSectionByAuthorId { get; set; }
        public string Suggestions { get; set; }

        public int FinalSectionId { get; set; }
        public virtual Section FinalSection { get; set; }

        public int UserId { get; set; }
        public virtual User Author { get; set; }
        
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Pdf> Pdf { get; set; }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView.Textual;
using urednistvo.ModelsView.Utilities;

namespace urednistvo.Controllers
{
    public class CommentController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        public static CommentView createCommentView(Comment comment)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {

                CommentView cView = new CommentView();

                cView.Content = comment.Content;
                cView.TextId = comment.TextId;
                cView.TextTitle = db.Texts.Single(t => t.TextId == comment.TextId).Title;
                cView.Time = comment.Time;
                cView.UserId = comment.UserId;
                cView.Username = db.Users.Single(u => u.UserId == comment.UserId).UserName;

                return cView;
            }
        }


        // GET: Comments
        public ActionResult Index()
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Comments
        public ActionResult ByText(int? id)
        {
            if(id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var query = from ord in db.Comments
                        where ord.TextId == id
                        select ord;

            List<CommentView> commentViews = new List<CommentView>();
            if (query.Count() == 0)
            {
                return View(commentViews);
            }
            
            foreach(Comment comment in query)
            {
                commentViews.Add(createCommentView(comment));
            }
            return View(commentViews);
        }

        public ActionResult ByUser(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (db.Ratings.Count(r => r.UserId == id) == 0)
            {
                TempData["Message"] = "Nema komentara ovog korisnika.";
                return RedirectToAction("Index", "Text");
            }

            var query = from ord in db.Comments
                        where ord.UserId == id
                        select ord;

            List<CommentView> commentViews = new List<CommentView>();
            foreach(Comment comment in query)
            {
                commentViews.Add(createCommentView(comment));
            }
            return View(commentViews);
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create/5
        public ActionResult Create(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (Session["UserID"] == null)
            {
                TempData["Message"] = "Registrirajte se ili logirajte da bi komentirali.";
                return RedirectToAction("Details/" + id, "Text");
            }
            string Role = ((string)Session["Role"]);
            if(Role != RoleNames.REGISTERED_USER && Role != RoleNames.AUTHOR)
            {
                TempData["Message"] = "Autori i registrirani korisnici imaju pravo komentirati.";
                return RedirectToAction("Details/" + id, "Text");
            }

            return View();
        }

        // POST: Comments/Create/5
        [HttpPost]
        public ActionResult Create(int id, Comment comment)
        {
            if (ModelState.IsValid)
            {
                using (UrednistvoDatabase db = new UrednistvoDatabase())
                {
                    
                    comment.Time = DateTime.Now;
                    comment.UserId = Int32.Parse((String)Session["UserID"]);
                    comment.TextId = id;

                    //return Content(comment.Content + " " + comment.Time + " " + comment.UserId + " " + comment.TextId);

                    db.Comments.Add(comment);
                    db.SaveChanges();
                }
                ModelState.Clear();
                TempData["Message"] = "Komentar je uspjesno stvoren.";

                return RedirectToAction("Details/" + comment.TextId, "Text");
            }
            return View();
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView;
using urednistvo.ModelsView.Textual;

namespace urednistvo.Controllers
{
    public class SectionsController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        private static SectionView createSectionView(Section section)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                SectionView sView = new SectionView();
                sView.SectionId = section.SectionId;
                sView.Title = section.Title;
                sView.NumberOfTexts = db.Texts.Count(t => t.FinalSectionId == sView.SectionId);

                return sView;
            }
        }

        public static SectionView createSectionView(Section section, DateTime start, DateTime end)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                SectionView sView = new SectionView();
                sView.SectionId = section.SectionId;
                sView.Title = section.Title;
                sView.NumberOfTexts = db.Texts.Count(t => ((t.WebPublishable == true && t.TextStatus == (int)TextStatus.LECTORED) ||
                                                    (t.EditionPublishable == true && t.TextStatus == (int)TextStatus.CORRECTED)) &&
                                                        t.Time < end &&
                                                        t.Time > start && t.FinalSectionId == section.SectionId);

                return sView;
            }
        }

        // GET: Sections
        public ActionResult Index()
        {
            List<SectionView> list = new List<SectionView>();
            foreach (Section s in db.Sections.ToList())
            {
                list.Add(createSectionView(s));
            }
            return View(list);
        }

        // GET: Sections/Details/5
        public ActionResult Details(int id)
        {
            List<Text> list = db.Texts.Where(s => s.FinalSectionId == id).ToList();
            if(list.Count == 0)
            {
                TempData["Message"] = "Nema tekstova u ovom podlistku.";
                return RedirectToAction("Index");
            }

            List<TextView> textViews = new List<TextView>();

            foreach (Text t in list)
            {
                textViews.Add(TextController.getTextView(t, false));
            }

            return View(textViews);
        }

        // GET: Sections/Details/5
        public ActionResult DetailsByEdition(int SectionId, int EditionId)
        {
            Edition edition = db.Editions.Find(EditionId);

            if(edition == null)
            {
                TempData["Message"] = "Greska kod trazenja teksta.";
                RedirectToAction("Details/" + SectionId);
            }

            DateTime end = edition.TimeOfRelease;
            DateTime start = edition.TimeOfRelease.AddDays(-7);

            List<Text> list = db.Texts.Where(t => ((t.WebPublishable == true && t.TextStatus == (int)TextStatus.LECTORED) ||
                                                    (t.EditionPublishable == true && t.TextStatus == (int)TextStatus.CORRECTED)) &&
                                                        t.Time < end &&
                                                        t.Time > start && t.FinalSectionId == SectionId).ToList();
            if (list.Count == 0)
            {
                TempData["Message"] = "Nema tekstova u ovom podlistku za odabrano izdanje.";
                return RedirectToAction("Index");
            }

            List<TextView> textViews = new List<TextView>();

            foreach (Text t in list)
            {
                textViews.Add(TextController.getTextView(t, false));
            }

            return View(textViews);
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView;
using urednistvo.ModelsView.Utilities;

namespace urednistvo.Controllers
{
    public class UserController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        public static UserView createUserView(User user)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                UserView uView = new UserView();

                uView.UserId = user.UserId;
                uView.Email = user.Email;
                uView.FirstName = user.FirstName;
                uView.LastName = user.LastName;
                uView.Role = db.Roles.Find(user.Role).RoleName;
                uView.UserName = user.UserName;

                return uView;
            }
        }

        // GET: User
        public ActionResult Index()
        {
            if(Session["UserID"] == null)
            {
                TempData["Message"] = "Samo registrirani korisnici mogu vidjeti popis korisnika.";
                RedirectToAction("Index", "Home");
            } 
            using(UrednistvoDatabase db = new UrednistvoDatabase())
            {
                List<UserView> userViews = new List<UserView>();

                foreach(User u in db.Users.ToList())
                {
                    userViews.Add(createUserView(u));
                }
                return View(userViews);
            }
        }

        public ActionResult Register()
        {
            ViewBag.DropDownList = new SelectList(db.Roles, "RoleId", "RoleName");
            return View();
        }

        [HttpPost]
        public ActionResult Register(User account)
        {
            if (ModelState.IsValid)
            {
                if(db.Users.Any(u => u.UserName == account.UserName))
                {
                    TempData["Message"] = "Korisničko ime " + account.UserName + " već postoji.";
                    return RedirectToAction("Register") ;
                }
                using (UrednistvoDatabase db = new UrednistvoDatabase())
                {
                    account.Role = db.Roles.Single(r => r.RoleName == RoleNames.REGISTERED_USER).Value;
                    db.Users.Add(account);
                    db.SaveChanges();
                }
                ModelState.Clear();
                Session["UserID"] = account.UserId.ToString();
                Session["Username"] = account.UserName.ToString();
                Session["Role"] = db.Roles.Find(account.Role).RoleName;

                TempData["Message"] = account.FirstName + " " + account.LastName + " uspješno registiran.";
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User account)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                var query = from u in db.Users
                            where u.UserName.Equals(account.UserName) &&
                                u.Password.Equals(account.Password)
                            select u;
                var user = query.FirstOrDefault();
                if(user != null)
                {
                    Session["UserID"] = user.UserId.ToString();
                    Session["Username"] = user.UserName.ToString();
                    Session["Role"] = db.Roles.Find(user.Role).RoleName;

                    TempData["Message"] = "Uspješna prijava.";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Korisničko ime ili lozinka pogrešni.");
                }
            }
            return View();
        }

        public ActionResult Logoff()
        {
            Session["UserID"] = null;
            Session["Username"] = null;
            Session["Role"] = null;

            TempData["Message"] = "Uspješno ste odjavljeni.";
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(int id)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                var user = db.Users.Single(d => d.UserId == id);
                return View(createUserView(user));
            }
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Views/Archive/Author.cshtml
@model urednistvo.ModelsView.UserView

@{
    ViewBag.Title = "Detalji o korisniku";
}

<h2>Korisnički detalji</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            Korisničko ime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Uloga
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Povratak u arhivu tekstova", "Index") |
    @Html.ActionLink("Komentari korisnika", "ByUser/" + Model.UserId, "Comment") |
    @Html.ActionLink("Moji tekstovi", "ByAuthor/" + Model.UserId, "Text") 
</p>

IzvorniKod/urednistvo/urednistvo/Views/Archive/Comment.cshtml
@model List<urednistvo.ModelsView.Textual.CommentView>

@{
    ViewBag.Title = "Komentari po tekstu";
}

<h2>Po tekstu</h2>

<table class="table">
    <tr>
        <th>
            Autor
        </th>
        <th>
            Sadržaj
        </th>
        <th>
            Ažurirano
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var comment in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Details/" + @comment.UserId, "User")'>
                    <span class="glyphicon glyphicon-user"></span> @comment.Username
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => comment.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => comment.Time)
            </td>
        </tr>
    }

</table>


<p>
    @Html.ActionLink("Uređivanje (nedefinirano)", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Povratak u arhivu tekstova", "Index", "Archive")
</p>

IzvorniKod/urednistvo/urednistvo/Views/Archive/Index.cshtml
@model List<urednistvo.ModelsView.Textual.TextView>

@{
    ViewBag.Title = "Arhiva";
}

<h2>Arhiva</h2>
<br />

<table class="table">
    <tr>
        <th>
            Naslov
        </th>
        <th>
            Autor
        </th>
        <th>
            Podlistak
        </th>
        <th>
            Ažurirano
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var text in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Text/" + @text.TextId, "Archive")'>
                    <span class="glyphicon glyphicon-list"></span> @text.Title (@text.Subtitle)
                </a>
            </td>

            <td>
                <a href='@Url.Action("Author/" + @text.UserId, "Archive")'>
                    <span class="glyphicon glyphicon-user"></span> @text.Username
                </a>

            <td>
                @if (text.FinalSectionId != -1)
                {
                    <a href='@Url.Action("Details/" + @text.FinalSectionId, "Sections")'>
                        <span class="glyphicon glyphicon-file"></span> @text.FinalSection
                    </a>
                }
                else
                {
                    <label><span class="glyphicon glyphicon-file"></span> @text.FinalSection </label>
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => text.Time)
            </td>

            <td>
                <a href='@Url.Action("Details/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-comment" title="Komentari"></span>
                </a>
            </td>

            <td>
                <a href='@Url.Action("Details/" + @text.TextId, "Ratings")'>
                    <span class="glyphicon glyphicon-star" title="Ocjene"></span>
                </a>
            </td>
            <td>
                <a href='@Url.Action("Download/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-download" title="Preuzmi"></span>
                </a>
            </td>
        </tr>
    }

</table>

<p>
    <font size="3">@Html.ActionLink("Dodaj tekst u arhivu", "Upload")</font>
</p>

IzvorniKod/urednistvo/urednistvo/Views/Archive/Text.cshtml
@model urednistvo.ModelsView.Textual.TextView

@{
    ViewBag.Title = "Detalji o tekstu";
}

<h2>
    Detalji teksta "@Model.Title"
</h2>
<br />

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Naslov
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            Podnaslov
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subtitle)
        </dd>

        <dt>
            Sadržaj
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            Ažurirano
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

    </dl>
</div>

@if ((String)Session["UserID"] == Model.UserId.ToString())
{
    <div>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                Status teksta
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TextStatus)
            </dd>

            <dt>
                Objavljeno na webu
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WebPublishable)
            </dd>

            <dt>
                Poslano na uređivanje
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EditionPublishable)
            </dd>

            <dt>
                Prijedlozi
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Suggestions)
            </dd>

            <dt>
                Željeni podlistak
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WantedSectionByAuthor)
            </dd>

            <dt>
                Konačni podlistak
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FinalSection)
            </dd>

        </dl>
    </div>
}

<p>
    @if ((String)Session["Role"] == "Glavni urednik" && Model.TextStatus == "Poslan")
    {
        @Html.ActionLink("Konačna ocjena", "EditEditor", new { id = Model.TextId });
        <label> |</label>
    }
    @if (((String)Session["Role"] == "Glavni urednik" || (String)Session["Role"] == "Član uredničkog vijeća") && Model.TextStatus == "Poslan")

    {
        @Html.ActionLink("Ocijeni", "EditMember", new { id = Model.TextId });
        <label> |</label>
    }
    @Html.ActionLink("Povratak u arhivu tekstova ", "Index") <label> | </label>
    @Html.ActionLink("Komentari na tekst", "Comment/" + Model.TextId, "Archive")
</p>

IzvorniKod/urednistvo/urednistvo/Views/Archive/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Dodavanje teksta u arhivu</h2>
<br />

<style>
    p.groove {
        width: 100px;
        padding: 5px;
        border: 2px solid black;
        margin: 2;
    }
</style>
<h3> Format teksta</h3>
<br />
<p>
    Predani tekst treba biti u rtf formatu i UTF8 encoding <br />
    te u sljedećem obliku:
</p>
<p class="groove">
    Naslov <br />
    dd/mm/yyyy <br />
    <br />
    Teksta

</p>
<br />

<form action="" method="post" enctype="multipart/form-data">

    <label for="file">Odaberi tekst:</label>
    <input type="file" name="file" id="file" />

    <input type="submit" value="OK" />
</form>