IzvorniKod/urednistvo/urednistvo/Models/Text.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace urednistvo.Models
{
    public class Text
    {
        public int TextId { get; set; }

        public string Title { get; set; }
        public string Subtitle { get; set; }
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }
        public DateTime Time { get; set; }

        public int TextStatus { get; set; } //enum
        public bool WebPublishable { get; set; }
        public bool EditionPublishable { get; set; }
        public int? WantedSectionByAuthorId { get; set; }
        public string Suggestions { get; set; }

        public int FinalSectionId { get; set; }
        public virtual Section FinalSection { get; set; }

        public int UserId { get; set; }
        public virtual User Author { get; set; }
        
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Pdf> Pdf { get; set; }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView.Textual;
using urednistvo.ModelsView.Utilities;

namespace urednistvo.Controllers
{
    public class CommentController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        public static CommentView createCommentView(Comment comment)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {

                CommentView cView = new CommentView();

                cView.Content = comment.Content;
                cView.TextId = comment.TextId;
                cView.TextTitle = db.Texts.Single(t => t.TextId == comment.TextId).Title;
                cView.Time = comment.Time;
                cView.UserId = comment.UserId;
                cView.Username = db.Users.Single(u => u.UserId == comment.UserId).UserName;

                return cView;
            }
        }


        // GET: Comments
        public ActionResult Index()
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Comments
        public ActionResult ByText(int? id)
        {
            if(id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var query = from ord in db.Comments
                        where ord.TextId == id
                        select ord;

            List<CommentView> commentViews = new List<CommentView>();
            if (query.Count() == 0)
            {
                return View(commentViews);
            }
            
            foreach(Comment comment in query)
            {
                commentViews.Add(createCommentView(comment));
            }
            return View(commentViews);
        }

        public ActionResult ByUser(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (db.Ratings.Count(r => r.UserId == id) == 0)
            {
                TempData["Message"] = "Nema komentara ovog korisnika.";
                return RedirectToAction("Index", "Text");
            }

            var query = from ord in db.Comments
                        where ord.UserId == id
                        select ord;

            List<CommentView> commentViews = new List<CommentView>();
            foreach(Comment comment in query)
            {
                commentViews.Add(createCommentView(comment));
            }
            return View(commentViews);
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create/5
        public ActionResult Create(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (Session["UserID"] == null)
            {
                TempData["Message"] = "Registrirajte se ili logirajte da bi komentirali.";
                return RedirectToAction("Details/" + id, "Text");
            }
            string Role = ((string)Session["Role"]);
            if(Role != RoleNames.REGISTERED_USER && Role != RoleNames.AUTHOR)
            {
                TempData["Message"] = "Autori i registrirani korisnici imaju pravo komentirati.";
                return RedirectToAction("Details/" + id, "Text");
            }

            return View();
        }

        // POST: Comments/Create/5
        [HttpPost]
        public ActionResult Create(int id, Comment comment)
        {
            if (ModelState.IsValid)
            {
                using (UrednistvoDatabase db = new UrednistvoDatabase())
                {
                    
                    comment.Time = DateTime.Now;
                    comment.UserId = Int32.Parse((String)Session["UserID"]);
                    comment.TextId = id;

                    //return Content(comment.Content + " " + comment.Time + " " + comment.UserId + " " + comment.TextId);

                    db.Comments.Add(comment);
                    db.SaveChanges();
                }
                ModelState.Clear();
                TempData["Message"] = "Komentar je uspjesno stvoren.";

                return RedirectToAction("Details/" + comment.TextId, "Text");
            }
            return View();
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView.Utilities;
using urednistvo.ModelsView;

namespace urednistvo.Controllers
{
    public class ImageController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        // GET: Image
        public ActionResult Index()
        {
            if((String)Session["Role"] != RoleNames.EDITOR && (String)Session["Role"] != RoleNames.GRAPHIC_EDITOR)
            {
                TempData["Message"] = "Nemate ovlasti pristupiti ovoj stranici.";
                return RedirectToAction("Index", "Text");
            }

            return View(db.Images.ToList());
        }

        // GET: Image/Details/5
        public ActionResult Details(int? id)
        {
            if ((String)Session["Role"] != RoleNames.EDITOR && (String)Session["Role"] != RoleNames.GRAPHIC_EDITOR)
            {
                TempData["Message"] = "Nemate ovlasti pristupiti ovoj stranici.";
                return RedirectToAction("Index", "Text");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        public ActionResult ByText(int? id)
        {
            if ((String)Session["Role"] != RoleNames.EDITOR && (String)Session["Role"] != RoleNames.GRAPHIC_EDITOR)
            {
                TempData["Message"] = "Nemate ovlasti pristupiti ovoj stranici.";
                return RedirectToAction("Index", "Text");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Text text = db.Texts.Find(id);
            if (text == null)
            {
                return HttpNotFound();
            }

            var images = db.Images.Where(i => i.TextId == id);
            if(images.Count() == 0)
            {
                TempData["Message"] = "Nema slika za ovaj tekst.";
                return RedirectToAction("ForGraphicEditing", "Text");
            }

            return View(images.ToList());
        }

        // GET: Image/Create
        public ActionResult Create(int id)
        {
            if ((String)Session["Role"] != RoleNames.EDITOR)
            {
                TempData["Message"] = "Nemate ovlasti pristupiti ovoj stranici.";
                return RedirectToAction("Index", "Text");
            }

            ViewBag.TextId = new SelectList(db.Texts.Where(t => t.TextStatus == (int)TextStatus.LECTORED && t.EditionPublishable == true), "TextId", "Title");
            return View();
        }

        // POST: Image/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Image image, HttpPostedFileBase file)
        {
            if (file != null)
            {
                string pic = System.IO.Path.GetFileName(file.FileName);
                string type = pic.Substring(pic.LastIndexOf(".")+1);

                string path = System.IO.Path.Combine(
                                       Server.MapPath("~/Images"), image.ImageName + "." + type);

                file.SaveAs(path);

                image.Type = type;
                db.Images.Add(image);
                db.SaveChanges();

            }
            return RedirectToAction("ForAddingImages", "Text");
        }

        public ActionResult Download(int? id)
        {
            if ((String)Session["Role"] != RoleNames.EDITOR && (String)Session["Role"] != RoleNames.GRAPHIC_EDITOR)
            {
                TempData["Message"] = "Nemate ovlasti pristupiti ovoj stranici.";
                return RedirectToAction("Index", "Text");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }

            string path = Server.MapPath("~/Images/" + image.ImageName + "." + image.Type);
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = image.ImageName + "." + image.Type;
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView;
using urednistvo.ModelsView.Utilities;

namespace urednistvo.Controllers
{
    public class UserController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        public static UserView createUserView(User user)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                UserView uView = new UserView();

                uView.UserId = user.UserId;
                uView.Email = user.Email;
                uView.FirstName = user.FirstName;
                uView.LastName = user.LastName;
                uView.Role = db.Roles.Find(user.Role).RoleName;
                uView.UserName = user.UserName;

                return uView;
            }
        }

        // GET: User
        public ActionResult Index()
        {
            if(Session["UserID"] == null)
            {
                TempData["Message"] = "Samo registrirani korisnici mogu vidjeti popis korisnika.";
                RedirectToAction("Index", "Home");
            } 
            using(UrednistvoDatabase db = new UrednistvoDatabase())
            {
                List<UserView> userViews = new List<UserView>();

                foreach(User u in db.Users.ToList())
                {
                    userViews.Add(createUserView(u));
                }
                return View(userViews);
            }
        }

        public ActionResult Register()
        {
            ViewBag.DropDownList = new SelectList(db.Roles, "RoleId", "RoleName");
            return View();
        }

        [HttpPost]
        public ActionResult Register(User account)
        {
            if (ModelState.IsValid)
            {
                if(db.Users.Any(u => u.UserName == account.UserName))
                {
                    TempData["Message"] = "Korisničko ime " + account.UserName + " već postoji.";
                    return RedirectToAction("Register") ;
                }
                using (UrednistvoDatabase db = new UrednistvoDatabase())
                {
                    account.Role = db.Roles.Single(r => r.RoleName == RoleNames.REGISTERED_USER).Value;
                    db.Users.Add(account);
                    db.SaveChanges();
                }
                ModelState.Clear();
                Session["UserID"] = account.UserId.ToString();
                Session["Username"] = account.UserName.ToString();
                Session["Role"] = db.Roles.Find(account.Role).RoleName;

                TempData["Message"] = account.FirstName + " " + account.LastName + " uspješno registiran.";
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User account)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                var query = from u in db.Users
                            where u.UserName.Equals(account.UserName) &&
                                u.Password.Equals(account.Password)
                            select u;
                var user = query.FirstOrDefault();
                if(user != null)
                {
                    Session["UserID"] = user.UserId.ToString();
                    Session["Username"] = user.UserName.ToString();
                    Session["Role"] = db.Roles.Find(user.Role).RoleName;

                    TempData["Message"] = "Uspješna prijava.";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Korisničko ime ili lozinka pogrešni.");
                }
            }
            return View();
        }

        public ActionResult Logoff()
        {
            Session["UserID"] = null;
            Session["Username"] = null;
            Session["Role"] = null;

            TempData["Message"] = "Uspješno ste odjavljeni.";
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(int id)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                var user = db.Users.Single(d => d.UserId == id);
                return View(createUserView(user));
            }
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Views/Text/Details.cshtml
@model urednistvo.ModelsView.Textual.TextView
@{
    ViewBag.Title = "Detalji o tekstu";
}
<h2>
    <strong>@Model.Title</strong> 
</h2>
<h3 style="padding-left:0.5em">
    @Html.DisplayFor(model => model.Subtitle)
</h3>

<br />
<div class="col-md-12" style="padding-top:1em; padding-bottom:1em; background-color:#eefce8; border-radius:75px">
   <div class="col-md-10 col-md-offset-1" >
       <hr />
       <text style="font-size:medium">@Model.Content</text>
       <hr/>
       @*@Html.DisplayFor(model => model.Content)*@
       <div class="row">
           <p>
               <span style="float:left">Autor: </span>
               <a href='@Url.Action("Details/" + @Model.UserId, "User")' style="float:left">
                   <span class="glyphicon glyphicon-user"></span> @Model.Username
               </a>
               @*<span style="float:left">Autor: @Model.Username</span>*@
               <span style="float:right">Objava: @Html.DisplayFor(model => model.Time)</span>
           </p>
       </div>
   </div>
    
</div>

@if ((String)Session["UserID"] == Model.UserId.ToString())
{
    <div class="col-md-12">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Status teksta
            </dt>
            <dd>
                <label>@Model.TextStatus</label>
            </dd>
         
            <dt>
                Prijedlozi
            </dt>
            <dd>
                <label>@Model.Suggestions</label>
            </dd>
            <dt>
                Željeni podlistak
            </dt>
            <dd>
                <label>@Model.WantedSectionByAuthor</label>
            </dd>
            <dt>
                Konačni podlistak
            </dt>
            <dd>
                <label>@Model.FinalSection</label>
            </dd>
            <dt>
                Za web
            </dt>
            <dd>
                @if (Model.WebPublishable == "True")
                {
                    <span class="glyphicon glyphicon-check" title=""></span>
                }
                else
                {
                    <span class="glyphicon glyphicon-minus" title=""></span>
                }
            </dd>
            <dt>
                Za tiskovinu
            </dt>
            <dd>
                @if (Model.EditionPublishable == "True")
                {
                    <span class="glyphicon glyphicon-check" title=""></span>
                }
                else
                {
                    <span class="glyphicon glyphicon-minus" title=""></span>
                }
            </dd>
        </dl>
    </div>
}
<p> 
    @if (Session["UserID"] != null)
    {
        if (Int32.Parse((string)Session["UserID"]) == Model.UserId && Model.TextStatus == "Vraćen")
        {
            @Html.ActionLink("Doradi", "Edit", new { id = Model.TextId });
            <label> |</label>
        }
        if ((String)Session["Role"] == "Glavni urednik" && Model.TextStatus == "Poslan")
        {
            @Html.ActionLink("Konačna ocjena", "EditEditor", new { id = Model.TextId });
        <label> |</label>
        }
        if (((String)Session["Role"] == "Glavni urednik" || (String)Session["Role"] == "Član uredničkog vijeća") && Model.TextStatus == "Poslan")

        {
            @Html.ActionLink("Ocijeni", "EditMember", new { id = Model.TextId });
            <label> |</label>
        }
    }
        
</p>

<div class="col-md-12">
    @Html.Action("Details", "Text", Model.TextId)
    <div class="row col-md-12" style="min-height:2em">
        @if (Session["UserID"] != null)
        {
            <a href='@Url.Action("Create/" + @Model.TextId, "Comment")'>
                <span class="glyphicon glyphicon-comment" title="Komentiraj"></span> Ostavi svoj komentar! 
            </a>
            <span>|</span> @Html.ActionLink("Povratak na listu tekstova ", "Index")
        }
    </div>
    
</div>

IzvorniKod/urednistvo/urednistvo/Views/Text/ForAddingImages.cshtml
@model List<urednistvo.ModelsView.Textual.TextView>
@{
    ViewBag.Title = "Tekstovi";
}
<h2>Dodavanje slika uz tekst</h2>
<br />
<table class="table">
    <tr>
        <th>
            Naslov
        </th>
        <th>
            Autor
        </th>
        <th>
            Podlistak
        </th>
        <th>
            Vrijeme
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var text in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(@text.Title + "(" + @text.Subtitle + ")", "Details/" + @text.TextId, "Text")
            </td>
            <td>
                @Html.ActionLink(@text.Username + " ", "Details/" + @text.UserId, "User")
            </td>
            <td>
                @if (text.FinalSectionId != -1)
                {
                    <a href='@Url.Action("Details/" + @text.FinalSectionId, "Sections")'>
                        <span class="glyphicon glyphicon-file"></span> @text.FinalSection
                    </a>
                }
                else
                {
                    <label><span class="glyphicon glyphicon-file"></span> @text.FinalSection </label>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => text.Time)
            </td>
            <td>
                <a href='@Url.Action("Download/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-download" title="Preuzmi tekst"></span>
                </a>
            </td>
            <td>
                <a href='@Url.Action("Create/" + @text.TextId, "Image")'>
                    <span class="glyphicon glyphicon-picture" title="Dodaj sliku"></span>
                </a>
            </td>
            <td>
                @Html.ActionLink("Zaključaj", "EndAddingPic/" + @text.TextId, "Text")
            </td>
        </tr>
    }
</table>

IzvorniKod/urednistvo/urednistvo/Views/Text/ForGraphicEditing.cshtml
@model List<urednistvo.ModelsView.Textual.TextView>
@{
    ViewBag.Title = "Tekstovi";
}
<h2>Tekstovi za grafičko uređivanje</h2>
<br />
<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Author
        </th>
        <th>
            Section
        </th>
        <th>
            Time
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var text in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(@text.Title + "(" + @text.Subtitle + ")", "Details/" + @text.TextId, "Text")
            </td>
            <td>
                @Html.ActionLink(@text.Username + " ", "Details/" + @text.UserId, "User")
            </td>
            <td>
                @if (text.FinalSectionId != -1)
                {
                    <a href='@Url.Action("Details/" + @text.FinalSectionId, "Sections")'>
                        <span class="glyphicon glyphicon-file"></span> @text.FinalSection
                    </a>
                }
                else
                {
                    <label><span class="glyphicon glyphicon-file"></span> @text.FinalSection </label>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => text.Time)
            </td>
            <td>
                <a href='@Url.Action("Download/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-download" title="Preuzmi tekst"></span>
                </a>
            </td>
            <td>
                <a href='@Url.Action("ByText/" + @text.TextId, "Image")'>
                    <span class="glyphicon glyphicon-picture" title="Pregledaj slike"></span>
                </a>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @using (Html.BeginForm("UploadRTF/" + @text.TextId, "Text", FormMethod.Post, new { id = "attachment", enctype = "multipart/form-data", encoding = "multipart/form-data" }))
                        {

                            <input type="file" value="Pretraži..." name="uploadFile" id="uploadFile" title="Pretraži..." />
                            <input type="submit" value="Predaj RTF" />
                        }
                        </div>
                    </div>

                        
                    </td>

        </tr>
    }
</table>

IzvorniKod/urednistvo/urednistvo/Views/Text/Index.cshtml
@model List<urednistvo.ModelsView.Textual.TextView>

@{
    ViewBag.Title = "Arhiva";
}

<h2>Svi tekstovi</h2>
<br /> 
@foreach(var t in Model.GroupBy(t => t.FinalSectionId))
{
    <div class="col-md-12" style="background-color:#eefce8">
        @if (t.Key != -1)
        {
            <a href='@Url.Action("Details/" + @t.Key, "Sections")' style="font-size:large">
                 @t.FirstOrDefault(x => x.FinalSectionId == t.Key).FinalSection
            </a>
        }
        else
        {
            <a style="font-size:large">@t.FirstOrDefault(x => x.FinalSectionId == t.Key).FinalSection </a>
        }
    </div>
    foreach(var text in t)
    {
        <div class="col-md-12" >
            <div class="col-md-1">
                <div class="col-md-6"  style="padding-top:2em">
                    <a href='@Url.Action("Details/" + @text.TextId, "Text")'>
                        <span class="glyphicon glyphicon-comment" title="Komentari"></span>
                    </a>
                </div>
                @if (text.EditionPublishable == "True")
                {
                    <div class="col-md-6" style="padding-top:2em">
                        <a href='@Url.Action("DownloadRTF/" + @text.TextId, "Text")' >
                            <span class="glyphicon glyphicon-download" title="Preuzmi"></span>
                        </a>
                    </div>
                }
                
            </div>
            <div class="col-md-9 " >
                <h3 >
                    <a href='@Url.Action("Details/" + @text.TextId, "Text")'>
                        @text.Title
                    </a> 
                </h3>
                <h4>
                    @text.Subtitle
                </h4>
                <p class="row">
                    <a href='@Url.Action("Details/" + @text.UserId, "User")'>
                        <span class="glyphicon glyphicon-user"></span> @text.Username
                    </a>
                    <span style="float:right">@Html.DisplayFor(modelItem => text.Time)</span>
                </p>
            </div>
            <div class="col-md-2" style="padding-left:3em">
                @if (Session["UserID"] != null)
                {
                   <div class="row" style="padding-top:1em">
                       <p>
                           <a href='@Url.Action("ByText/" + @text.TextId, "Ratings")'>
                               <span class="glyphicon glyphicon-star" title="Ocjene"></span>
                           </a>
                           <a href='@Url.Action("Edit/" + @text.TextId, "Text")'>
                               <span class="glyphicon glyphicon-pencil" title="Uređivanje"></span>
                           </a>
                           <a href='@Url.Action("Delete/" + @text.TextId, "Text")'>
                               <span class="glyphicon glyphicon-trash" title="Obriši"></span>
                           </a>
                       </p>
                   </div>
                    if (text.WebPublishable == "True")
                    {
                        <div class="row">
                            <p>Za web: <span class="glyphicon glyphicon-check" title=""></span></p>
                        </div>
                    }
                }
                @if ((String)Session["Role"] == "Glavni urednik")
                {
                    <p>Status: @Html.DisplayFor(modelItem => text.TextStatus)</p>
                }

            </div>

        </div>
    }
}

@*<table class="table">
    <tr>
        <th>
            Naslov
        </th>
        <th>
            Autor
        </th>
        <th>
            Podlistak
        </th>
        <th>
            Ažurirano
        </th>
        @if ((String)Session["Role"] == "Glavni urednik")
        {
            <th>
                Text status
            </th>
        }
        <th>
            Za web
        </th>
        <th>
            Za tiskovinu
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var text in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Details/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-list"></span> @text.Title (@text.Subtitle)
                </a>
            </td>

            <td>
                <a href='@Url.Action("Details/" + @text.UserId, "User")'>
                    <span class="glyphicon glyphicon-user"></span> @text.Username
                </a>

            </td>
            <td>
                @if (text.FinalSectionId != -1)
                {
                    <a href='@Url.Action("Details/" + @text.FinalSectionId, "Sections")'>
                        <span class="glyphicon glyphicon-file"></span> @text.FinalSection
                    </a>
                }
                else
                {
                    <label><span class="glyphicon glyphicon-file"></span> @text.FinalSection </label>
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => text.Time)
            </td>

            @if ((String)Session["Role"] == "Glavni urednik")
            {
                <th>
                    @Html.DisplayFor(modelItem => text.TextStatus)
                </th>
            }

            <td>
                @if (text.WebPublishable == "True")
                {
                    <span class="glyphicon glyphicon-check" title=""></span>
                }
            </td>

            <td>
                @if (text.EditionPublishable == "True")
                {
                    <a href='@Url.Action("DownloadRTF/" + @text.TextId, "Text")'>
                        <span class="glyphicon glyphicon-download" title="Preuzmi"></span>
                    </a>
                    
                }
            </td>

            <td>
                <a href='@Url.Action("ByText/" + @text.TextId, "Comment")'>
                    <span class="glyphicon glyphicon-comment" title="Komentari"></span>
                </a>
            </td>

            <td>
                <a href='@Url.Action("ByText/" + @text.TextId, "Ratings")'>
                    <span class="glyphicon glyphicon-star" title="Ocjene"></span>
                </a>
            </td>
             @if (Session["UserID"] != null)
             {
                <td>
                    <a href='@Url.Action("Edit/" + @text.TextId, "Text")'>
                        <span class="glyphicon glyphicon-pencil" title="Uređivanje"></span>
                    </a>
                </td>
                <td>
                    <a href='@Url.Action("Delete/" + @text.TextId, "Text")'>
                        <span class="glyphicon glyphicon-trash" title="Obriši"></span>
                    </a>
                </td>
             }
            
        </tr>
    }

</table>*@

@if (Session["UserID"] != null)
{
    <p>
        <font size="3">@Html.ActionLink("Novi tekst", "Create")</font>
    </p>
}