IzvorniKod/urednistvo/urednistvo/Models/Edition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace urednistvo.Models
{
    public class Edition
    {
        public int EditionId { get; set; }
        [Required(ErrorMessage = "Tiskovina mora imati naslov")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Invalid")]
        public string Title { get; set; }
        public DateTime TimeOfRelease { get; set; }

        public virtual ICollection<Section> Sections { get; set; }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/EditionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView;
using urednistvo.ModelsView.Textual;

namespace urednistvo.Controllers
{
    public class EditionsController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        public static EditionView createEditionView(Edition edition)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                EditionView eView = new EditionView();
                eView.EditionId = edition.EditionId;
                eView.Title = edition.Title;
                eView.TimeOfRelease = edition.TimeOfRelease;
                eView.StartTime = eView.TimeOfRelease.AddDays(-7);
                eView.NumberOfTexts = db.Texts.Where(t => ((t.WebPublishable == true && t.TextStatus == (int)TextStatus.LECTORED) ||
                                                    (t.EditionPublishable == true && t.TextStatus == (int)TextStatus.CORRECTED)) &&
                                                        t.Time < eView.TimeOfRelease &&
                                                        t.Time > eView.StartTime).Count();
                return eView;
            }
        }

        // GET: Editions
        public ActionResult Index()
        {
            List<EditionView> eViews = new List<EditionView>();
            foreach (Edition e in db.Editions.ToList())
            {
                eViews.Add(createEditionView(e));
            }
            return View(eViews);
        }

        // GET: Editions/Details/5
        public ActionResult Details(int? id)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                Edition edition = db.Editions.Single(e => e.EditionId == id);
                DateTime end = edition.TimeOfRelease;
                DateTime start = edition.TimeOfRelease.AddDays(-7);

                List<Section> sections = db.Sections.ToList();
                List<SectionView> sViews = new List<SectionView>();

                foreach (Section s in sections)
                {
                    sViews.Add(SectionsController.createSectionView(s, start, end));
                }

                return View(new Tuple<List<SectionView>, Edition>(sViews, edition));
            }
        }

        public ActionResult EditionTexts(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Edition edition = db.Editions.Find((int)id);
            if (edition == null)
            {
                return HttpNotFound();
            }

            EditionView eView = createEditionView(edition);
            List<Text> texts = db.Texts.Where(t => ((t.WebPublishable == true && t.TextStatus == (int)TextStatus.LECTORED) ||
                                                    (t.EditionPublishable == true && t.TextStatus == (int)TextStatus.CORRECTED)) &&
                                                        t.Time < eView.TimeOfRelease &&
                                                        t.Time > eView.StartTime).ToList();

            if(texts.Count == 0)
            {
                TempData["Message"] = "Nema tekstova u ovom izdanju.";
                return RedirectToAction("Index");
            }

            List<TextView> textViews = new List<TextView>();
            foreach(Text t in texts)
            {
                textViews.Add(TextController.getTextView(t, false));
            }

            return View(textViews);
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using urednistvo.Models;
using urednistvo.ModelsView;
using urednistvo.ModelsView.Utilities;

namespace urednistvo.Controllers
{
    public class UserController : Controller
    {
        private UrednistvoDatabase db = new UrednistvoDatabase();

        public static UserView createUserView(User user)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                UserView uView = new UserView();

                uView.UserId = user.UserId;
                uView.Email = user.Email;
                uView.FirstName = user.FirstName;
                uView.LastName = user.LastName;
                uView.Role = db.Roles.Find(user.Role).RoleName;
                uView.UserName = user.UserName;

                return uView;
            }
        }

        // GET: User
        public ActionResult Index()
        {
            if(Session["UserID"] == null)
            {
                TempData["Message"] = "Samo registrirani korisnici mogu vidjeti popis korisnika.";
                RedirectToAction("Index", "Home");
            } 
            using(UrednistvoDatabase db = new UrednistvoDatabase())
            {
                List<UserView> userViews = new List<UserView>();

                foreach(User u in db.Users.ToList())
                {
                    userViews.Add(createUserView(u));
                }
                return View(userViews);
            }
        }

        public ActionResult Register()
        {
            ViewBag.DropDownList = new SelectList(db.Roles, "RoleId", "RoleName");
            return View();
        }

        [HttpPost]
        public ActionResult Register(User account)
        {
            if (ModelState.IsValid)
            {
                if(db.Users.Any(u => u.UserName == account.UserName))
                {
                    TempData["Message"] = "Korisničko ime " + account.UserName + " već postoji.";
                    return RedirectToAction("Register") ;
                }
                using (UrednistvoDatabase db = new UrednistvoDatabase())
                {
                    account.Role = db.Roles.Single(r => r.RoleName == RoleNames.REGISTERED_USER).Value;
                    db.Users.Add(account);
                    db.SaveChanges();
                }
                ModelState.Clear();
                Session["UserID"] = account.UserId.ToString();
                Session["Username"] = account.UserName.ToString();
                Session["Role"] = db.Roles.Find(account.Role).RoleName;

                TempData["Message"] = account.FirstName + " " + account.LastName + " uspješno registiran.";
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User account)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                var query = from u in db.Users
                            where u.UserName.Equals(account.UserName) &&
                                u.Password.Equals(account.Password)
                            select u;
                var user = query.FirstOrDefault();
                if(user != null)
                {
                    Session["UserID"] = user.UserId.ToString();
                    Session["Username"] = user.UserName.ToString();
                    Session["Role"] = db.Roles.Find(user.Role).RoleName;

                    TempData["Message"] = "Uspješna prijava.";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Korisničko ime ili lozinka pogrešni.");
                }
            }
            return View();
        }

        public ActionResult Logoff()
        {
            Session["UserID"] = null;
            Session["Username"] = null;
            Session["Role"] = null;

            TempData["Message"] = "Uspješno ste odjavljeni.";
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(int id)
        {
            using (UrednistvoDatabase db = new UrednistvoDatabase())
            {
                var user = db.Users.Single(d => d.UserId == id);
                return View(createUserView(user));
            }
        }
    }
}

IzvorniKod/urednistvo/urednistvo/Views/Editions/Details.cshtml
@model Tuple<List<urednistvo.ModelsView.Textual.SectionView>, urednistvo.Models.Edition>

@{
    ViewBag.Title = "Izdanje";
}

<h2>Detalji o izdanju</h2>

<table class="table">
    <tr>
        <th>
            Naslov odjeljka
        </th>
        <th>
            Broj tekstova
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model.Item1)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Title, "Details/" + item.SectionId, "Sections")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfTexts)
            </td>
            <td>
                @Html.ActionLink("Pregledaj tekstove", "DetailsByEdition", "Sections", new { SectionId = item.SectionId, EditionId = Model.Item2.EditionId}, null)
            </td>
        </tr>
    }

</table>

IzvorniKod/urednistvo/urednistvo/Views/Editions/EditionTexts.cshtml
@model List<urednistvo.ModelsView.Textual.TextView>

@{
    ViewBag.Title = "EditionTexts";
}

<h2>Svi tekstovi izdanja</h2>

<table class="table">
    <tr>
        <th>
            Naslov
        </th>
        <th>
            Autor
        </th>
        <th>
            Podlistak
        </th>
        <th>
            Ažurirano
        </th>
        @if ((String)Session["Role"] == "Glavni urednik")
        {
            <th>
                Text status
            </th>
        }
        <th>
            Za web
        </th>
        <th>
            Za tiskovinu
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var text in Model)
    {
        <tr>
            <td>
                <a href='@Url.Action("Details/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-list"></span> @text.Title (@text.Subtitle)
                </a>
            </td>

            <td>
                <a href='@Url.Action("Details/" + @text.UserId, "User")'>
                    <span class="glyphicon glyphicon-user"></span> @text.Username
                </a>

            <td>
                @if (text.FinalSectionId != -1)
                {
                    <a href='@Url.Action("Details/" + @text.FinalSectionId, "Sections")'>
                        <span class="glyphicon glyphicon-file"></span> @text.FinalSection
                    </a>
                }
                else
                {
                    <label><span class="glyphicon glyphicon-file"></span> @text.FinalSection </label>
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => text.Time)
            </td>

            @if ((String)Session["Role"] == "Glavni urednik")
            {
                <th>
                    @Html.DisplayFor(modelItem => text.TextStatus)
                </th>
            }

            <td>
                @if (text.WebPublishable == "True")
                {
                    <span class="glyphicon glyphicon-check" title=""></span>
                }
            </td>

            <td>
                @if (text.EditionPublishable == "True")
                {
                    <a href='@Url.Action("DownloadRTF/" + @text.TextId, "Text")'>
                        <span class="glyphicon glyphicon-download" title="Preuzmi"></span>
                    </a>
                }
            </td>

            <td>
                <a href='@Url.Action("Details/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-comment" title="Komentari"></span>
                </a>
            </td>

            <td>
                <a href='@Url.Action("ByText/" + @text.TextId, "Ratings")'>
                    <span class="glyphicon glyphicon-star" title="Ocjene"></span>
                </a>
            </td>
            <td>
                <a href='@Url.Action("Edit/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-pencil" title="Uređivanje"></span>
                </a>
            </td>
            <td>
                <a href='@Url.Action("Delete/" + @text.TextId, "Text")'>
                    <span class="glyphicon glyphicon-trash" title="Obriši"></span>
                </a>
            </td>
        </tr>
    }
</table>
<p>
    <font size="3">@Html.ActionLink("Novi tekst", "Create")</font>
</p>

IzvorniKod/urednistvo/urednistvo/Views/Editions/Index.cshtml
@model List<urednistvo.ModelsView.Textual.EditionView>

@{
    ViewBag.Title = "Izdanja";
}

<h2>Popis dosadašnjih izdanja</h2>

<table class="table">
    <tr>
        <th>
            Naslov
        </th>
        <th>
            Vrijeme objave
        </th>
        <th>
            Broj tekstova
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <label>@item.Title</label>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeOfRelease)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfTexts)
        </td>
        <td>
            @Html.ActionLink("Po podlistcima", "Details/" + item.EditionId, "Editions")
        </td>
        <td>
            @Html.ActionLink("Popis tekstova", "EditionTexts/" + item.EditionId, "Editions")
        </td>
    </tr>
}

</table>